apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../policies/namespaces.yaml
  - ../../policies/prometheus-rules.yaml
  - ../../apps/resource-catalog/k8s.yaml
  - ../../apps/docs-site
  - ../../tenants/etri
  - ../../apps/mlops
  - ../../apps/kueue/queues.yaml
  - ../../apps/kubeflow/tenant-launchers
