apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
  - https://github.com/kubeflow/pipelines/manifests/kustomize/base/installs/generic?ref=2.17.0
  - https://github.com/kubeflow/pipelines/manifests/kustomize/base/metadata/base?ref=2.17.0
  - https://github.com/kubeflow/pipelines/manifests/kustomize/third-party/argo/installs/namespace?ref=2.17.0
  - https://github.com/kubeflow/pipelines/manifests/kustomize/third-party/mysql/base?ref=2.17.0
  - storage-aliases.yaml
  - artifact-env.yaml
  - minio-init-job.yaml
  - networkpolicy.yaml
patches:
  - path: delete-unsupported-cache-server.yaml
  - path: delete-unsupported-cache-service.yaml
  - path: delete-upstream-example-secret.yaml
  - path: pipeline-config-patch.yaml
  - path: workflow-config-patch.yaml
  - path: api-server-patch.yaml
  - path: ui-patch.yaml
  - path: mysql-patch.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          environment: cloud
          kubernetes.io/arch: amd64
