apiVersion: v1
kind: ConfigMap
metadata:
  name: pipeline-install-config
data:
  appVersion: "2.17.0"
  dbType: mysql
  mysqlHost: mysql
  mysqlPort: "3306"
  mlmdDb: metadb
  cacheDb: cachedb
  pipelineDb: mlpipeline
  bucketName: kubeflow-pipelines
  defaultPipelineRoot: s3://kubeflow-pipelines/v2/artifacts
  defaultSecurityContextRunAsUser: "10001"
  defaultSecurityContextRunAsGroup: "10001"
  defaultSecurityContextRunAsNonRoot: "true"
  defaultSecurityContextHostUsers: "false"
  BLOCK_V1_PIPELINES: "true"
