apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  artifactRepository: |
    archiveLogs: true
    s3:
      endpoint: seaweedfs.kubeflow.svc.cluster.local:9000
      bucket: kubeflow-pipelines
      keyFormat: "private-artifacts/{{workflow.namespace}}/{{workflow.name}}/{{pod.name}}"
      insecure: true
      accessKeySecret:
        name: kubeflow-artifact-store
        key: accesskey
      secretKeySecret:
        name: kubeflow-artifact-store
        key: secretkey
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kfp-launcher
data:
  defaultPipelineRoot: s3://kubeflow-pipelines/v2/artifacts
  providers: |
    s3:
      default:
        endpoint: seaweedfs.kubeflow.svc.cluster.local:9000
        region: us-east-1
        disableSSL: true
        forcePathStyle: true
        maxRetries: 5
        credentials:
          fromEnv: false
          secretRef:
            secretName: kubeflow-artifact-store
            accessKeyKey: accesskey
            secretKeyKey: secretkey
      overrides: []
