FROM 192.168.0.56:5000/mini-science-ai-os:0.3.1

COPY overrides/science_os/job_api.py /opt/science-ai/services/science_os/job_api.py
COPY overrides/science_os/resource_catalog.py /opt/science-ai/services/science_os/resource_catalog.py
COPY overrides/science_os/portal/favicon.svg /opt/science-ai/services/science_os/portal/favicon.svg
COPY overrides/science_os/portal/index.html /opt/science-ai/services/science_os/portal/index.html
COPY overrides/science_os/portal/portal.css /opt/science-ai/services/science_os/portal/portal.css
COPY overrides/science_os/portal/portal.js /opt/science-ai/services/science_os/portal/portal.js
